name: 'Synchronize changes to cloud'
description: 'Synchronize changes to cloud'
inputs:
  cloud-repository-url:
    description: 'Url of the cloud repository to sync'
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone cloud repo
      run: git clone ${{ inputs.cloud-repository-url}} ..\cloud-repository
      shell: powershell
    - name: Create artifact for cloud
      run: |
            md -Force ..\cloud-artifact
            Copy-Item .\.git ..\cloud-artifact
            Copy-Item .\.git\* ..\cloud-artifact\.git -force -recurse
            Copy-Item .\*.web\* ..\cloud-artifact -force -recurse
            Copy-Item .\*.site\* ..\cloud-artifact -force -recurse
      shell: powershell
    - name: Run KuduSync.Net
      run: C:\.\DeploymentScripts\RunKuduSyncNet.ps1 "..\cloud-artifact" "..\cloud-repository" ".git;.github;nuget.config" "${{github.run_number}}"
      shell: powershell
    - name: Commit and push to Cloud
      run: |
            cd ..\cloud-repository
            C:\.\DeploymentScripts\CommitAndPushToCloud.ps1 "${{github.run_number}}"
      shell: powershell