name: 'Synchronize changes to cloud'
description: 'Synchronize changes to cloud'
inputs:
  cloud-repository-url:
    description: 'Url of the cloud repository to sync'
    required: true
  from-dir:
    description: 'Path to the current repository directory'
    required: true
  to-dir:
    description: 'Path to the sync repository directory'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install kudusync
      run: npm install -g kudusync
      shell: powershell
    - name: Clone cloud repo
      run: git clone ${{ inputs.cloud-repository-url}} ${{ inputs.to-dir }}
      shell: powershell
    - name: Kudusync
      run: kudusync --fromDir ${{ inputs.from-dir }} --toDir ${{ inputs.to-dir }} --ignore "${{ env.TO_CLOUD_KUDUSYNC_IGNORE }}" --nextManifest ../kudusyncmanifest.txt --ignoreManifest
      shell: powershell
    - name: Create wwwroot .gitignore
      run: |
        New-Item -Path ${{ inputs.to-dir }}${{ env.WWWROOT_PATH }} -Name ".gitignore" -Value "${{ env.WWWROOT_GITIGNORE_RULES }}" -Force
      shell: powershell
    - name: Copy Assets
      run: | 
        $dst = Get-ChildItem "${{ inputs.to-dir }}/*/wwwroot"
        Select-Object -First 1 -Expand FullName     
        Copy-Item -Path "${{ env.app-path }}/wwwroot/assets" -Destination "$($dst)/assets" -recurse -Force
      shell: powershell
    - name: Commit and push to Cloud
      run: |
            cd ${{ inputs.to-dir }}
            C:\.\DeploymentScripts\CommitAndPushToCloud.ps1 "${{github.run_number}}"
      shell: powershell